apiVersion: v1
kind: Config
clusters:
  - name: webhook-authn
    cluster:
      server: https://192.168.65.2
users:
  - name: authn-user
current-context: webhook
contexts:
  - context:
      cluster: webhook-authn
      user: authn-user
    name: webhook                

# kubectl config set-context --current --user=auth-test
# kubectl get pods --token="system:masters;minikube-user;password"  

