apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kube-authorization-webhook
  name: kube-authorization-webhook
spec:
  containers:
  - image: martinsimango/kube-authorization-webhook
    name: kube-authorization-webhook
    resources: {}
    ports:
      - containerPort: 80
      - containerPort: 443

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
