apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: kube-authorization-webhook
  name: kube-authorization-webhook-svc
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    name: "https"
  - port: 80
    protocol: TCP
    targetPort: 80
    name: "http"
  selector:
    run: kube-authorization-webhook
  type: NodePort
status:
  loadBalancer: {}
